### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by sooluh** [GabrielNBDS/plutus#1]
Hello @GabrielNBDS, I'm interested in this!
However, I'm from Indonesia and I don't understand Brazilian at all. Maybe using English as the main language of this website can help non-Brazilians.
And I hope there is multi language support using i18n module from AdonisJS.
Thank you :)

**Comment by sooluh** [comment]
I'd be happy to contribute to translating it into Indonesian!

**Comment by GabrielNBDS** [comment]
Hello.
Thanks, I really appreciate your interest. Once I add i18n to it I'll let you know. I'll work on this still this week.

**Comment by GabrielNBDS** [comment]
@sooluh I made the changes and hopefully I covered everything. Please try and check.

Changes required to add a new language:

- Add the language in `/config/i18n.ts -> supportedLocales`
- Add the translations in `/resources/lang`
- Add the currency in `/start/loaders.ts`

**Comment by sooluh** [comment]
Amazing, I will contribute ASAP :grin:
